<?php
    include("../inc/header.php");
?>

    <div class="rel section">
        <div class="axiataBold">
            <p class="text__color--lightgrey font25">Axiata <span class="block text__color--lightred font31">National Contribution</p>
        </div>

        <div class="row text__color--darkgrey  font15">
            <div class="font15 text__color--lightred axiataBold">Commitment to Long-Term Investment in All Our Countries</div>
            <div>
                <div class="text-justify">
                    <p>The Group makes a direct and indirect contribution to the economies of the countries in which it operates. Axiata’s contribution includes new jobs, both directly and indirectly, new investments, training for employees, leadership opportunities across the Group and consequently across the region, access to state-of-the-art digital technology, the integration of greener technology and processes, facilitating the growth of the global telecommunications industry, and investments in disaster resilience, education, e-innovation and social inclusion.</p>
                    <p>Our 2013 Sustainability Report included a National Contribution Report using methodology developed by an independent party. For 2014, we asked the same independent third party to assess our contribution in our operating countries and provide updated data. </p>
                    <p>This part of the report is based on the data generated by the independent third party as evidence of the contributions Axiata has made in 2014 in the several countries of Asia in which we operate.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col col50">
                <div class="contribution">
                    fsafsa
                </div>
            </div>
            <div class="col col50">

            </div>
            <div class="col col50">

            </div>
            <div class="col col50">

            </div>
            <div class="col col50">

            </div>
            <div class="col col50">

            </div>
            <div class="col col50">

            </div>
            <div class="col col50">
                <div class="col col80">
                    <div class="font9 text__color--darkgrey">
                        <p>* excludes idea and M1</p>
                        <p>Axiata’s 2014 Sustainability and National Contribution Report, Committed to Development, Towards a Digital Future is available online at www.axiata.com and can be downloaded on AppStore and GooglePlay. </p>
                    </div>
                </div>
                <div class="col col20">
                    <img src="../assets/img/chapter1/nr/ch_1_contribution.png">
                </div>
            </div>

        </div>
    </div>

</div>

<?php
    include("../inc/footer.php");
?>

