<?php

    include("../inc/header.php");

?>
<link rel="stylesheet" href="../assets/css/National_Contribution/National_Contribution.css">

<section id="nationalContributionSection" style="margin-top:75px;">
	<div style="width:960px; padding:55px; margin:0 auto; box-sizing:border-box;">
		<div style="line-height:1;">
			<span class="title grey8Color" style="font-size:25px;">National</span><br />
			<span class="title maroonColor" style="font-size:31px;">Contribution</span>
		</div>
	</div>
	<div class="grey4Color" style="width:960px; padding:55px; margin:0 auto; box-sizing:border-box; margin-top:-80px;">
		<span class="title maroonColor">National Contribution Report</span><br />
		<br />
		Axiata group provides state of the art digital technology and through its investments contribute directly and indirectly to the economies of the countries in which it operates. Our employees across the region benefit from the availability of training and leadership opportunities in line with the growth of Axiata and the global telecommunications industry as a whole. Axiata’s contribution introduces new job opportunities, integration of green technology and process, disaster resilience, education, e-innovation and social inclusion amongst others.<br />
		<br />
		Our 2014 Sustainability Report, similar to last year includes a National Contribution Report using methodology developed by an independent party. This year we have the same independent third party to assessing our contribution in our operating countries and provide updated data.<br />
		<br />
		This part of the report is based on the data generated by the independent third party as evidence of the contributions Axiata has made in 2014 in the several countries of Asia in which we operate.<br />
		<br />
		<span class="title maroonColor">Our Economic and Social Contribution Since 2008</span>
	</div>
	<div style="width:960px; padding:55px; margin:0 auto; box-sizing:border-box; margin-top:-90px;">
		<img src="../assets/img/national/National_Contribution/table.png" />
	</div>
	<div class="grey4Color" style="width:960px; padding:55px; margin:0 auto; box-sizing:border-box; margin-top:-90px; font-size:10px;">
		* Does not Include Idea and M1<br />
  	<span style="margin-left:7px; font-size:10px;">View the methodology used for calculation.</span>
	</div>
</section>
<?php
	include("../inc/footer.php");
	?>